# Node 3 Configuration
server.port=8083

# Cluster Configuration
cluster.node-id=3
cluster.total-nodes=5
cluster.write-quorum=5
cluster.read-quorum=1
cluster.network-delay-ms=0
cluster.read-delay-ms=50

# Peer nodes (all other nodes except this one)
cluster.peers[0]=http://10.245.222.64:8081
cluster.peers[1]=http://10.245.222.64:8082
cluster.peers[2]=http://10.245.222.64:8084
cluster.peers[3]=http://10.245.222.64:8085

# Logging
logging.level.com.cs6650.leaderlesskv=DEBUG