FROM eclipse-temurin:17-jre
WORKDIR /app
COPY target/leaderless-kv-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8090
ENV JAVA_OPTS="-Xmx512m -Xms256m"
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
