product.service.url=http://ecommerce-alb-2060929212.us-west-2.elb.amazonaws.com
shopping.cart.service.url=http://ecommerce-alb-2060929212.us-west-2.elb.amazonaws.com
credit.card.service.url=http://ecommerce-alb-2060929212.us-west-2.elb.amazonaws.com
warehouse.service.url=http://ecommerce-alb-2060929212.us-west-2.elb.amazonaws.com

# Optimized configuration
total.checkouts=200000
items.per.cart=1
thread.count=128
max.retries=5

connection.timeout=15000
request.timeout=30000

metrics.output.file=test_64threads_1item_10k.csv
results.output.file=test_64threads_1item_10k.txt

rabbitmq.management.url=http://34.222.152.255:15672
